create table public.policy_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  policy_name text,
  feedback text,
  submitted_by text,
  status text not null default 'new'
);

alter table public.policy_feedback enable row level security;

create policy "Admins can view all feedback"
on public.policy_feedback for select
using ( get_user_role(auth.uid()) = ANY (ARRAY['admin'::user_role, 'super-admin'::user_role]) );

create policy "Users can insert their own feedback"
on public.policy_feedback for insert
with check (true);
